### ISSUE TITLE
keyerror after `r2env add radare2`

### ISSUE THREAD

**Issue by trufae** [radareorg/r2env#1]
As reported in https://github.com/radareorg/r2ghidra/issues/29

```
# r2env add radare2
Adding package
Building radare2
Cloning into '/home/.r2env/src/radare2@git'...
remote: Enumerating objects: 232649, done.
remote: Counting objects: 100% (274/274), done.
remote: Compressing objects: 100% (152/152), done.
remote: Total 232649 (delta 145), reused 218 (delta 121), pack-reused 232375
Receiving objects: 100% (232649/232649), 132.71 MiB | 3.04 MiB/s, done.
Resolving deltas: 100% (179389/179389), done.
Building ...
tail -f /home/.r2env/log/radare2.txt
Traceback (most recent call last):
  File "/usr/local/bin/r2env", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/r2env/repl.py", line 177, in main
    if not run_action(e, args.action, args.args):
  File "/usr/local/lib/python3.8/dist-packages/r2env/repl.py", line 143, in run_action
    if not match_pkg(pkgs, targets, add_package):
  File "/usr/local/lib/python3.8/dist-packages/r2env/repl.py", line 96, in match_pkg
    cb(pkg, profile)
  File "/usr/local/lib/python3.8/dist-packages/r2env/repl.py", line 49, in add_package
    pkg.build(profile)
  File "/usr/local/lib/python3.8/dist-packages/r2env/db/radare2.py", line 107, in build
    build_radare2(profile)
  File "/usr/local/lib/python3.8/dist-packages/r2env/db/radare2.py", line 86, in build_radare2
    use_meson = profile["meson"]
KeyError: 'meson'
```

**Comment by as0ler** [comment]
Should be fixed with the new r2env version. Try "r2env install radare2@latest"
