### ISSUE TITLE
`r2env add radare2@5.9.0` fails if ~/.r2env/src/radare2 is older than the 5.9.0 release

### ISSUE THREAD

**Issue by eliminmax** [radareorg/r2env#36]
As the title states, `r2env add radare2@5.9.0` fails if the source repo directory already exists, but was cloned before the `5.9.0` release tag existed. Manually fetching the latest tags fixes it.

I assume that the same failure would occur for any new tag.

Now that I have an up-to-date version of the repo, I can't reproduce the issue. I didn't keep track of the exact error messages I saw or steps I took to fix it on my machine. I plan on restoring ~/.r2env/src/radare2/ from a backup and trying to reproduce it, keeping better notes of my progress. I might also open a pull request to fix the issue - I might have some idea about how to fix it, but I need to test it before going through with it.

**Comment by eliminmax** [comment]
The exact Traceback is as follows:
```
[*] Installing radare2@5.9.0 package from source
[-] Cloning 5.9.0 version
Traceback (most recent call last):
  File "/home/eliminmax/.local/pipx/bin/r2env", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/eliminmax/.local/pipx/venvs/r2env/lib/python3.11/site-packages/r2env/repl.py", line 116, in main
    REPL().run_action(action_args)
  File "/home/eliminmax/.local/pipx/venvs/r2env/lib/python3.11/site-packages/r2env/repl.py", line 96, in run_action
    self.actions[action](args[0], use_meson=action_args.meson, use_dist=action_args.package)
  File "/home/eliminmax/.local/pipx/venvs/r2env/lib/python3.11/site-packages/r2env/core.py", line 79, in install
    self._package_manager.install_package(profile, version, use_meson=use_meson, use_dist=use_dist)
  File "/home/eliminmax/.local/pipx/venvs/r2env/lib/python3.11/site-packages/r2env/package_manager.py", line 162, in install_package
    if self._build_from_source(profile, version, source_path, dst_dir, logfile, use_meson=use_meson):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eliminmax/.local/pipx/venvs/r2env/lib/python3.11/site-packages/r2env/package_manager.py", line 278, in _build_from_source
    git_fetch(self._packages[profile]["source"], version, source_path)
  File "/home/eliminmax/.local/pipx/venvs/r2env/lib/python3.11/site-packages/r2env/tools.py", line 84, in git_fetch
    repo.git.checkout(version)
  File "/home/eliminmax/.local/pipx/venvs/r2env/lib/python3.11/site-packages/git/cmd.py", line 741, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eliminmax/.local/pipx/venvs/r2env/lib/python3.11/site-packages/git/cmd.py", line 1315, in _call_process
    return self.execute(call, **exec_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eliminmax/.local/pipx/venvs/r2env/lib/python3.11/site-packages/git/cmd.py", line 1109, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git checkout 5.9.0
  stderr: 'error: pathspec '5.9.0' did not match any file(s) known to git'

```

**Comment by eliminmax** [comment]
Given that the fix for this was merged a few months back, I think this issue should be closed after the next release of `r2env`.

**Comment by trufae** [comment]
released, sorry for the delay

**Comment by eliminmax** [comment]
No worries! Appreciate it.
